name: cypress-cucumber-pom-pipeline-jenkins
on: 
  push:
    branches:
      - "stage"
      - "main"
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Clean global cache
        run: npm cache clean --force
        
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.3.0
        with:
          start: npm run runOnChromeTerminal
        
       
